### ISSUE TITLE
iOS Consumables stuck in unfinished state

### ISSUE THREAD

**Issue by jason2211** [jamesmontemagno/InAppBillingPlugin#102]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:  1.2.3.107 (and using latest from GitHub)
Device Tested On: iPhone 5s
Simulator Tested On: N/A
Version of VS: VS 2017 v15.4.4
Version of Xamarin:  4.7.10.38

### Steps to reproduce the Behavior
Start purchase of a consumable and have an exception prevent the library from calling the FinishTransaction.  This leaves the consumable in a Purchased state in the store.  When the user attempts to purchase again they receive the Apple message "This In-App Purchase has already been bought.  It will be restored for free.".  After the user clicks ok, the InAppBillingPlugin library never completes the Task.  The user is not able to re-purchase this consumable.

The item is returned from GetPurchasesAsync call even though it is a consumable.

I modified the RestoreAsync method in the iOS InAppBillingImplementation class to call the FinishTransaction.  This removed the consumable item from the user and allowed it to be purchase again.  However, I don't think this is the correct approach.

### Expected Behavior
It would be nice if the call to PurchaseAsync could detect the orphaned transaction, complete it, then pass the purchase details back to the calling application.

I tried my best to set breakpoints all over the implementation class but could not find any callbacks from the AddPayment call.  The handler doesn't seem to be called in this scenario.

So, if my expected behavior isn't possible, it would be nice if the calling application had the option to "consume / finalize transaction" for this item after calling GetPurchasesAsync similar to the Android implementation.

### Actual Behavior
No information is returned to the application about the purchase when calling PurchaseAsync.  The task never completes.

When calling GetPurchasesAsync, the consumable item comes back with the following info: 
{ProductId:coin500 | AutoRenewing:False | State:Purchased | Id:1000000363989250}

**Comment by mccadi** [comment]
Can verify this happens to me as well.

**Comment by meepou** [comment]
I have the same issue as well.

**Comment by Atomico001** [comment]
I have this problem too...

**Comment by meepou** [comment]
I have the same problem.
This is quite a main issue as when iOS prompt user to add a new payment method it stucks the purchased item in this pending state.

**Comment by meepou** [comment]
Ok so I managed to find a workaround.

When my app starts, I check if there is an item with the PurchaseState.Purchased in the list returned by GetPurchasesAsync, if there is, I activate the product on my server.

Then in order to make the item disappear from the purchased products list for the AppStore Account, I finish the transaction. To do so, I downloaded the library and wrote a new method :

```
public async override Task<bool> FinishTransaction(InAppBillingPurchase purchase)
		{
			var purchases = await RestoreAsync();

			if (purchases == null)
				return false;

			var transaction = purchases.Where(p => p.TransactionIdentifier == purchase.Id).FirstOrDefault();
			if (transaction != null)
				SKPaymentQueue.DefaultQueue.FinishTransaction(transaction);

			return true;
		}
```

In my code, I do:

```
var purchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);

            if (purchases.Where(p => p.State == PurchaseState.Purchased).Any())
            {
                var purchase = purchases.Where(p => p.State == PurchaseState.Purchased).FirstOrDefault();

                // Activate the item on my server

                var finished = await CrossInAppBilling.Current.FinishTransaction(purchase);
            }
```

**Comment by bertoldofonseca** [comment]
It's also happening to me.

The weird part is that no one from the project has commented here.
Is this project dead?

**Comment by mccadi** [comment]
Me and my employers have actually left Xamarin and are now developing with Flutter.io!

**Comment by jamesmontemagno** [comment]
hey @meepou how does my PR look for this? I added FinishTransaction so you can manually finish it if needed

**Comment by meepou** [comment]
Looking nice, thank you James. It allows us to be able to manage those weird unfinished states !

Keep up the good work 

As I said, unfortunately, I rewrote my whole implementation of InAppPurchases directly with StoreKit. I had an issue when a user had no payment method on its account, it would redirect to the AppStore to add a payment method and the item was "lost" (because it is a non-renewing subscription).

**Comment by bertoldofonseca** [comment]
Thanks, James. You made my day.
Looking forward to seeing this fix in action.

BR

**Comment by mnxamdev** [comment]
I'm working on another issue and noticed that the Beta version of the plugin now has these FinishTransaction methods in the interface which need to be implemented. Why and what do we need to do in those methods? In our case we are selling consumables that we then  verify with our servers. Do we need to use FinishTransaction now instead of using IInAppBillingVerifyPurchase.VerifyPurchase(...)? I didn't see any documentation in the Beta version of the Nuget package I downloaded or the website. I appreciate any insight you can offer.
