### ISSUE TITLE
Feature Request: Add MacOS Support

### ISSUE THREAD

**Issue by ShammyLevva** [jamesmontemagno/InAppBillingPlugin#202]
Could the iOS code be adapted with minimal effort to provide MacOS In App Purchase support?

**Comment by jamesmontemagno** [comment]
I will not be implementing it as I have no plans here, however anyone can send a PR.

**Comment by tussock** [comment]
It seems that the only reason that the InAppBilling.apple.cs uses UIKit is to perform:
`static bool IsiOS112 => UIDevice.CurrentDevice.CheckSystemVersion(11, 2);`
i.e. to see if the version is 11.2 or later.

This is used later for introductory prices.
```
LocalizedIntroductoryPrice = IsiOS112 ? (p.IntroductoryPrice?.LocalizedPrice() ?? string.Empty) : string.Empty, 
MicrosIntroductoryPrice = IsiOS112 ? (long)((p.IntroductoryPrice?.Price?.DoubleValue ?? 0) * 1000000d) : 0
```

Otherwise, it looks like this code should be portable between mac and iOS.

Cheers.

**Comment by Suplanus** [comment]
@tussock 
I had a look into it... there are problems with `SkPayment` and `SkPaymentTransaction`:
![image](https://user-images.githubusercontent.com/2002916/104199991-697a9b80-5428-11eb-96a9-791504ad9600.png)

![image](https://user-images.githubusercontent.com/2002916/104200002-6d0e2280-5428-11eb-99ab-a9968d8b9b4a.png)

Have no idea how to handle the tokens.

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/InAppBillingPlugin/pull/354

Will be in 4.1.0 there will not be a transaction receipt though as you will need to call the native APIs for it
