### ISSUE TITLE
android billing with AIDL deprecated

### ISSUE THREAD

**Issue by Sevenish** [jamesmontemagno/InAppBillingPlugin#225]
The android implementation is based on Google Play Billing with AIDL. This is now deprecated. Google states ([developer.android.com/google/play/billing/api](https://developer.android.com/google/play/billing/api)): 

> Warning: AIDL is now deprecated and will be removed in a future release. To implement Google Play Billing features, use the Google Play Billing library 

Please update to use the official Google Play Billing Library Client (com.android.billingclient:billing:2.0.0)
[developer.android.com/google/play/billing/billing_library_overview](https://developer.android.com/google/play/billing/billing_library_overview).
Unfortunately Xamarin does not seem to provide a nuget wrapper for this official java library at this time.

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/jamesmontemagno/InAppBillingPlugin/issues/221

**Comment by mnxamdev** [comment]
@jamesmontemagno I don't believe this has been addressed yet. I pulled the android-billing-client branch and it looks like we are still using AIDL. Can we reopen this issue so that it can be addressed? I believe BillingClient is currently covered by Xamarin.Android.Google.BillingClient nuget package:
https://www.nuget.org/packages/Xamarin.Android.Google.BillingClient/
Thanks for all your efforts!
