### ISSUE TITLE
Sign-In Required?

### ISSUE THREAD

**Issue by K232** [jamesmontemagno/InAppBillingPlugin#229]
Is it the expected behaviour that I get the following message when I'm trying to buy a non-consumable good on iOS?

> **Sign-In Required**
> If you have an Apple ID,sign in with it here. If you have used the iTunes Store or iCloud, for example, you have an Apple ID.

In other apps, I could just confirm my purchase with touch id. Having an additional login form might confuse some users as it's not the default expected action. They are already logged in, so why log in again? Additionally there are probably some users don't knowing their ID and / or password. And some might be concerned about the security as this could be a login form within my own application, trying to grab users ID and password for Apple Store.

![MyApp](https://user-images.githubusercontent.com/685016/59145832-97e0fb00-89e9-11e9-9f4c-3f22fcaf3cfe.jpg)
![OtherApp](https://user-images.githubusercontent.com/685016/59145833-98799180-89e9-11e9-9e5a-f22310a17cf4.jpg)

So am I doing something wrong or is it just the way it is with Xamarin (Forms)?

**Comment by devology-rob** [comment]
I believe this is because it’s not a live release? 

If you’re using a sandbox environment then I believe you get that login box instead so you can enter test account details.

Our app uses the same plugin and it prompts the user for face / fingerprint on live, pretty sure elsewhere it’s that login dialog.

In their recent survey I did point out that test IAP is inconsistent and impossible for scenarios like out-of-band expired card scenarios etc.  This I believe is another example.

**Comment by K232** [comment]
Thanks for fast reply, @devology-rob 👍  
The procedure is also explained at [Test Purchase on Testflight](https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html) , but I wasn't sure about live.

But if it's working fine in your live release, I'm quite optimistic for my live release :-) Many thanks!!
