### ISSUE TITLE
Your server-side billing confirmations will stop working on December 1, 2019

### ISSUE THREAD

**Issue by nicolgit** [jamesmontemagno/InAppBillingPlugin#261]
I am receiving this message on playstore

_ACTION REQUIRED: Your server-side billing confirmations will stop working on December 1, 2019
Your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. Note that this is not related to the AIDL/Billing Library deprecation._ 

https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**AFAIK server side, I am using API V3. Can this message related to calls done by InAppBilling Plugin?**

**Comment by mgoodfellow** [comment]
Related to https://github.com/jamesmontemagno/InAppBillingPlugin/issues/221 ?

Granted, that message was slightly different, but it sounds like you aren't using API v3 on the server-side as that is what the warning is referencing.

The InAppBilling plugin does not make any server-side billing calls.

I just checked mine and I'm not receiving warnings since updating server side components - are you using .NET on the server side? If so, make sure you are using the https://www.nuget.org/packages/Google.Apis.AndroidPublisher.v3 library - same contracts as the other nugets, so simply a drop in replacement.

**Comment by nicolgit** [comment]
Server side, I am using version https://www.nuget.org/packages/Google.Apis.AndroidPublisher.v3/1.38.2.1573 that AFAIK is V3... or no?

**Comment by nicolgit** [comment]
Using of InAppBilling v3.0.0.0-preview fixed the issue
