### ISSUE TITLE
Small Documentation Change Possibly?

### ISSUE THREAD

**Issue by jamsoft** [jamesmontemagno/InAppBillingPlugin#392]
Whilst reading the Android testing documentation here:

https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

It mentions that the version being tested, for me this is VS debugging on hardware, that the version being tested must match a version uploaded to Google Play. Unless I've missed it, the docs here don't mention anything about that requirement:

https://developer.android.com/google/play/billing/test

"Ordinarily, the Google Play Billing Library is blocked for apps that aren't signed and uploaded to Google Play. License testers can bypass this check, meaning you can sideload apps for testing, even for apps using debug builds with debug signatures without the need to upload to the new version of your app. Note that the package name must match that of the app that is configured for Google Play, and the Google account must be a license tester for the Google Play Console account."

It seems that now you can rely solely on the bundle ID. Or have I missed something obvious?

**Comment by davidjade** [comment]
I would also add, that it is possible to test on the simulator as well even with a debug build. This is despite what Google docs say and I don't know why that is. But the catch is, you have to use a simulator image that includes the Play Store API AND you have to make the primary google account on the device/simulator one of the Internal track testers (and not your developer account). When you do this, you can debug all store APIs including purchases. And you can use all the test purchase methods (including "slow card" for pending payment tests).

Now this could be (and how this is related to the above) because I first installed an Internal Test track to the simulator and then overwrote it with a new debug build that used the same version numbers. This is also the way I tested a debug build on a real device as well, so it is essentially the same process for real devices and simulators as far as IAP testing goes.

I'll also add that I do not have the Android project signing set up as I let Google handle store app signing.

**Comment by jamesmontemagno** [comment]
i have made updates along the way, send prs if you want changes for me to review
