### ISSUE TITLE
Public key

### ISSUE THREAD

**Issue by bovp2000** [jamesmontemagno/InAppBillingPlugin#4]
If I do not care too much about the public key, where I can enter that key? I am new to xamarin and cannot get it working :( I obfuscated my code so it's secured enough for me.

**Comment by jamesmontemagno** [comment]
You have 3 options for Android. If you don't care at all about doing any validation simply pass in null or nothing for the IVerifyPayment. This will auto verify your payments for you. 

If you want to make sure they are verified and do not care about security due to obfuscation you can put the key in.

Or you can do the xor like i put in there.

To get your key it is different for each app. 

* Go to your Play Developer Console
* Select an App
* Select Services & APIs
* It is found under Licensing & In-App Billing
