### ISSUE TITLE
[Feature] Don't Finalize "Consumable" on iOS

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/InAppBillingPlugin#414]
Right now we finalize transactions automatically. We should give the option to not do this if it is a consumable.

See: https://github.com/jamesmontemagno/InAppBillingPlugin/issues/412

**Comment by edgiardina** [comment]
Upvoting this, it's a blocker that prevents us from using this lib. By calling FinishTransaction on a consumable in iOS, it removes the purchase from the receipt. In our setup we need to see the purchases during server side validation. When you use your lib, in_app is stripped from the receipt object.

https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/choosing_a_receipt_validation_technique#//apple_ref/doc/uid/TP40010573

> Consumable in-app purchases remain in the receipt until you call finishTransaction(_:). Non-consumables, auto-renewing subscription items, and non-renewing subscription items remain in the receipt indefinitely. For auto-renewable subscription management, see the following table for the key advantages that server-side receipt validation gives over on-device receipt validation. Apple Developer Documentation

**Comment by jamesmontemagno** [comment]
Any thought son implementation here.... I guess we also finish when we restore as well... can be very tricky i think....

**Comment by edgiardina** [comment]
@jamesmontemagno what are your concerns? I thought #412 did a good job explaining it. IMHO I would just behave like android? IF we bump this by a major version and indicate its a breaking change, I don't think its a problem. Also on #412 [najak3d](https://github.com/najak3d) seems to have an implementation already based on his testing. I'm happy to game it out / contribute.

**Comment by jamesmontemagno** [comment]
@edgiardina  and @najak3d checkout https://github.com/jamesmontemagno/InAppBillingPlugin/pull/444 and let me know thoughts here.

The idea is that ConsumePurchaseAsync will now call FinishTransaction on iOS, but now for all purchases you will have to manually call FinishTransactionAsync after you have unlocked it.

For back compat because maybe people don't care, they can set a static flag on iOS to turn on AutoFinishTransactions

**Comment by najak3d** [comment]
Ours work-around solution is working fine now "as is", so probably won't be validating your fixes here.  If we end up with any bugs that arise in our system, and I get back into this part of the code, the first thing we may do is to try out your fixes here, and see if that resolves our problem.

I think my description of the issue was pretty clear in #412, so I trust that your solution probably addresses the core issue I raised.  My purpose in posting was for sake of Xamarin-itself, making it a better/safer place to write apps, and iOS store integration should be on par with all other apps.   Hopefully, that is what your fix here achieved.

Thank you for your continued devotion, genius, and service.

**Comment by jamesmontemagno** [comment]
@najak3d thanks for all the details. I think I now have a good solution. I have introduced a new "ItemType.InAppPurchaseConsumable" and with this set then I wont finish it. Also on restore (get purchases) you can pass in Ids that are consumables and I wont finish those either. This should do it.

**Comment by jamesmontemagno** [comment]
5.3.0-beta dnad 6.3.0-beta have this now

**Comment by edgiardina** [comment]
This looks great, thank you. Of course, it would have been a lot less work if StoreKit/SKProduct had an IsConsumable flag when you fetch the product list, since when you configure the SKUs you have to provide that info. But your extra type appears to map well with [this doc I was reading the other day](https://betterprogramming.pub/in-app-purchases-and-storekit-in-ios-14-aed2c3e58966) 

Thanks James, appreciate the work you've done for Xamarin / MAUI community.
