### ISSUE TITLE
Google Play Billing Library 5/6

### ISSUE THREAD

**Issue by cdecron** [jamesmontemagno/InAppBillingPlugin#556]
Hello,
From November 1, 2023, Google will force app updates to implement Billing Library version 5.
[More information here](https://developer.android.com/google/play/billing/migrate-gpblv6)

Will InAppBillingPlugin be updated to implement Billing Library 5 or 6 instead of 4?

Thank you by advance

**Comment by ivmirx** [comment]
Already done, v7.x of this plugin uses Android Billing v6

**Comment by cjorgens79** [comment]
> Already done, v7.x of this plugin uses Android Billing v6

@ivmirx What about those of us using Xamarin, we have to use v5.x of this plugin, what version of Android Billing is that using?

**Comment by cdecron** [comment]
Indeed, I forgot to precise but I'm talking about Xamarin (Forms).
As @cjorgens79 says, it's recommended to use 5.x plugin version.

Can I know from which plugin version each of Billing Library 4, 5 and 6 are implemented? I didn't find it in the changes log.

Thank you

**Comment by roughiain** [comment]
Looking at the release notes for v5 it is version 4

<img width="997" alt="image" src="https://github.com/jamesmontemagno/InAppBillingPlugin/assets/19661735/b687af51-ec3d-4c32-8cb7-84ffcc3fc537">

**Comment by broda02** [comment]
Version 7.0.5 works just fine with Xamarin Forms.
Version 7.0.5 works fine with Xamarin Forms.  I use it in an Xamarin Forms App...

On 27 September 2023 at 00:56:37, cjorgens79 ***@***.***) wrote:

Already done, v7.x of this plugin uses Android Billing v6

@ivmirx What about those of us using Xamarin, we have to use v5.x of this plugin, what version of Android Billing is that using?

**Comment by najak3d** [comment]
@jamesmontemagno - We love your products!  Thank you for your service!

Can you please update the main description of this product to indicate which Release versions support which versions of Android's "Billing Library"  4, 5, or 6.

You already have a section called "Important Version Information" shown here;
https://github.com/jamesmontemagno/InAppBillingPlugin

Please add notes to this section regarding Android's "Billing Library" versions.

For us, until late next year, we'll remain on Xamarin, and so we need to make sure we're compliant with the Nov 2023 mandate using Xamarin.    We're currently using InApp Billing 5.6.1 from Sept 2022.   Is this compliant already with "Billing Lib 5?"??   

Since this is so crucial to know -- this should be highlighted on the front page, to make it easier to find.

**Comment by najak3d** [comment]
I see from another recent issue, that the ONLY version of this plugin that uses Android Billing 6 is the 7.0 release.   All others use Billing 4 Lib, and so won't work after Nov 1, 2023.

So your "Important Version Info" says for Xamarin (non-MAUI) apps, you recommend "version 5.x".

So what should Xamarin Forms Apps use?   5.6.1 won't work after Nov 1st, and 7.0 is "not recommended".  What to do?

Whatever this answer is -- should probably be put onto the top of the front page of this repo.

**Comment by Toine-db** [comment]
Version 7.0.5 seems to works fine with Xamarin Native (not tested with Forms)

I just upgraded from 6.7 and didn't change anything, all purchase functionalities I use seem to work on production.

**Comment by broda02** [comment]
I use 7.0.5 with Forms and all works fine


On 29 September 2023 at 12:04:18, Toine de Boer ***@***.***) wrote:

Version 7.0.5 seems to works fine with Xamarin Native (not tested with Forms)

I just upgraded from 6.7 and didn't change anything, all purchase functionalities I use seem to work on production.

**Comment by ivmirx** [comment]
@cjorgens79 I use it in Xamarin native

**Comment by najak3d** [comment]
I've upgraded too and it seems to work.  But I was hesitant to believe it until it's the "official recommendation".

So if it works, then I suppose the "Important Version Info" needs to be updated, because we can no longer keep the current recommendations, no longer compliant with the Play Store.

**Comment by cjorgens79** [comment]
I am using Xamarin Forms, sounds from the other comments like it works fine in that too.  Cheers

**Comment by imsam67** [comment]
I have a .NET MAUI app using version 7.0.5 of this plug-in but when I try to upload my `aab` file to Google Play, I'm getting the following error:

> This app targets Android 14 or above, and your current Play Billing Library version doesn't support Android 14. To target the latest Android version, please update your PBL version to either 5.2.1, or 6.0.1 and above.

According to earlier posts, version 7.0.5 of this plug-in already targets PBL 6 so I'm a bit confused.

My app is now targeting .NET 8 RC1 so in project file, it's `net8.0-android`. Because I'm not specifying any OS TFM, I believe .NET 8 targets Android 14. Has anyone run into this issue? Is it as simple as specifying an older OS TFM for Android?

**Comment by jamesmontemagno** [comment]
I update the readme with more information. v7 targets everything and is built against Google Play Library v6

**Comment by cdecron** [comment]
Thank you very much for your answers
