### ISSUE TITLE
[iOS 12.5.5] Why I'm geeting Sign-in to iTunes Store pop-up?

### ISSUE THREAD

**Issue by semdevel** [jamesmontemagno/InAppBillingPlugin#652]
Hello,

Can someone explain why I am getting this pop-up dialog on iOS MAUI? IPhone 6 iOS 12.5.5. Is there a way to prevent it? I already downloaded the app iTunes Store and it seems that I'm logged in, so why I'm getting this pop-up every time I run the app?

When I call this line of code, I always get described pop-up:

`var subs = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);`

Here is the pop-up image:

![IMG_027344444](https://github.com/user-attachments/assets/920b8e38-b9b5-4a73-b6ed-e447c3fdcfdf)

Please help, I got stuck here. Thank you for any help.

**Comment by rezamohamed** [comment]
This is because you are testing your app. You don't want to spend real money, so you need to create a Sandbox user in App Store Connect so that you can buy with fake money. 

![CleanShot 2024-11-26 at 14 59 53@2x](https://github.com/user-attachments/assets/341b3a54-349d-4eb4-a4fe-b18129ffd2e2)

Once you create your Sandbox account, you can login to that account in the screen you are seeing and you wont be charged. Once your app is released for Distribution, it will pickup the App Store account associated to the phone.
